# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=40, null=True, verbose_name='Текст тэга')),
                ('last_scraped', models.DateTimeField(verbose_name='Время последнего парсинга')),
                ('is_active', models.BooleanField(verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Хэштэг',
                'verbose_name_plural': 'Хэштэги',
            },
        ),
    ]
