# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_parsing', '0001_initial'),
        ('hashtags', '0003_auto_20170907_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Hashtag', 'verbose_name_plural': 'Hashtags'},
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='network_id',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_parsing.Network', verbose_name='Social network'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='is_active',
            field=models.BooleanField(verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='last_scraped',
            field=models.DateTimeField(verbose_name='Last parsing date and time'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tag'),
        ),
    ]
