# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0004_auto_20170907_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last parsing date and time'),
        ),
    ]
