# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0005_auto_20170907_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='is_active',
            field=models.NullBooleanField(verbose_name='Active'),
        ),
    ]
