# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_parsing', '0005_auto_20170927_2008'),
        ('hashtags', '0006_auto_20170907_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='network',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='network',
            field=models.ManyToManyField(blank=True, null=True, to='social_parsing.Network', verbose_name='Social network'),
        ),
    ]
