# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0007_auto_20171004_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='network',
            field=models.ManyToManyField(blank=True, to='social_parsing.Network', verbose_name='Social network'),
        ),
    ]
