# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор поста',
                'verbose_name_plural': 'Авторы постов',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование')),
                ('parsing_frequency', models.PositiveIntegerField(blank=True, default=60, null=True, verbose_name='Количество секунд между повторениями')),
            ],
            options={
                'verbose_name': 'Наименование соцсети',
                'verbose_name_plural': 'Наименования соцсетей',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('video', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на видео')),
                ('photo', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на фото')),
                ('elink', models.CharField(blank=True, max_length=400, null=True, verbose_name='Внешняя ссылка (если есть)')),
                ('link', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка')),
                ('lid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID поста в социальной сети')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('is_original', models.BooleanField(verbose_name='Оригинальный')),
                ('autor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_parsing.Author', verbose_name='Автор поста')),
                ('hashtag_id', models.ManyToManyField(blank=True, to='hashtags.HashTag', verbose_name='Хэштэг')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
