# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0004_auto_20170907_1129'),
        ('social_parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Post author', 'verbose_name_plural': 'Post authors'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Name of the social network', 'verbose_name_plural': 'Networks name'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_parsing.Author', verbose_name='Post author'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='hashtags.HashTag', verbose_name='Hashtag'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='The number of likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='mtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to database'),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='The number of shares'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Post content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Authors name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='parsing_frequency',
            field=models.PositiveIntegerField(blank=True, default=60, null=True, verbose_name='The number of seconds between parsing attempts.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='elink',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='External link (if exists in post)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_original',
            field=models.BooleanField(verbose_name='Original post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Post ID in social network'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Photo link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Video Link'),
        ),
    ]
