# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_parsing', '0002_auto_20170907_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lid',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Author's profile"),
        ),
    ]
