# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import social_parsing.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_parsing', '0003_auto_20170912_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='network',
            name='icon_pic',
            field=models.ImageField(blank=True, null=True, upload_to='network_pic/', validators=[social_parsing.models.Network.validate_image], verbose_name='Social network icon'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
