# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import social_parsing.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_parsing', '0004_auto_20170927_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='icon_pic',
            field=models.FileField(blank=True, null=True, upload_to='network_pic/', validators=[social_parsing.models.Network.validate_image], verbose_name='Social network icon'),
        ),
    ]
