# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0008_auto_20171004_0930'),
        ('social_parsing', '0005_auto_20170927_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTagNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Last parsing date and time')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtags.HashTag')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_parsing.Network')),
            ],
        ),
    ]
