# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170907_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refresh_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When limit will be renewed'),
        ),
    ]
