# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='URL строка должна иметь вид https://DOMAIN_OR_IP:PORT', max_length=1024)),
                ('expires', models.DateTimeField(verbose_name='Дата окончания оплаты прокси сервера')),
                ('is_active', models.BooleanField(verbose_name='Работает')),
                ('is_banned', models.BooleanField(verbose_name='В чёрном списке')),
            ],
            options={
                'verbose_name': 'Прокси адрес',
                'verbose_name_plural': 'Прокси адреса',
            },
        ),
    ]
