# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name': 'Proxy address', 'verbose_name_plural': 'Proxy addresses'},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='expires',
            field=models.DateTimeField(verbose_name='Pay expiration date and time'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_active',
            field=models.BooleanField(verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_banned',
            field=models.BooleanField(verbose_name='Blacklisted'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proxy URL'),
        ),
    ]
