# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleusers',
            name='bio',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='simpleusers',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
    ]
