# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_auto_20170911_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleusers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatar/', verbose_name='Users image'),
        ),
    ]
